version: '3.8'
services:
  go:
    container_name: go
    build: 
      context: ./infrastructure/golang
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./infrastructure/mysql/.env
    depends_on:
      - db
    volumes:
      - ./src:/go/src

  db:
    container_name: db
    build:
      context: ./infrastructure/mysql
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./infrastructure/mysql/.env


      
    