version: '3.8'
services:
  go:
    container_name: go
    build: 
      context: ./infrastructure/golang
      dockerfile: dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./infrastructure/mysql/.env
    depends_on:
      - db
    volumes:
      - ./src:/go/src
      - ./infrastructure/mysql/.env:/go/src/.env
  
  frontend:
    container_name: frontend
    tty: true
    build:
      context: ./infrastructure/frontend
      dockerfile: dockerfile
    volumes: 
      - ./frontend:/usr/src/app
    ports: 
      - "3000:3000"

  db:
    container_name: db
    build:
      context: ./infrastructure/mysql
      dockerfile: dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./infrastructure/mysql/.env
    volumes:
      - ./infrastructure/mysql/db:/var/lib/mysql


      
    